ARCH="armhf"
RUNNER="ubuntu24armhf"
IMAGE_URL="https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-armhf.img"
KERNEL_URL="https://cloud-images.ubuntu.com/noble/current/unpacked/noble-server-cloudimg-armhf-vmlinuz-generic"
INITRD_URL="https://cloud-images.ubuntu.com/noble/current/unpacked/noble-server-cloudimg-armhf-initrd-generic"
USE_UBUNTU_INIT="yes"
