ARCH="armhf"
RUNNER="ubuntu22"
IMAGE_URL="https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-armhf.img"
KERNEL_URL="https://cloud-images.ubuntu.com/jammy/current/unpacked/jammy-server-cloudimg-armhf-vmlinuz-lpae"
INITRD_URL="https://cloud-images.ubuntu.com/jammy/current/unpacked/jammy-server-cloudimg-armhf-initrd-generic-lpae"
USE_UBUNTU_INIT="yes"
