#!/bin/bash

set -e
set -o pipefail

SCRIPT_PATH="${BASH_SOURCE[0]}"
while [ -h "${SCRIPT_PATH}" ]
do
    SCRIPT_DIR="$(cd -P "$(dirname "${SCRIPT_PATH}")" &> /dev/null && pwd)"
    SCRIPT_PATH="$(readlink "${SCRIPT_PATH}")"
    [[ ${SCRIPT_PATH} != /* ]] && SCRIPT_PATH="${SCRIPT_DIR}/${SCRIPT_PATH}"
done
SCRIPT_DIR="$(cd -P "$(dirname "${SCRIPT_PATH}")" &> /dev/null && pwd)"
ROOT="$(cd -P "${SCRIPT_DIR}/../.." &> /dev/null && pwd)"

TMPDIR="$(mktemp -d)"

onexit() {
    rm -r -- "${TMPDIR}"
}
trap onexit EXIT

mkdir "${TMPDIR}/etc"
cp -r "${ROOT}/etc/fonts" "${TMPDIR}/etc/fonts"
mkdir -p "${TMPDIR}/var/cache/fontconfig"

fontconfreplace() {
    sed -i "s/${1//\//\\/}/${2//\//\\/}/g" "${TMPDIR}/etc/fonts/fonts.conf"
}
fontconfreplace "<dir>/usr/share/fonts</dir>" "<dir>${ROOT}/usr/share/fonts</dir>"
fontconfreplace "<dir>/usr/local/share/fonts</dir>" ""
fontconfreplace "<dir prefix=\"xdg\">fonts</dir>" ""
fontconfreplace "<dir>~/.fonts</dir>" ""
fontconfreplace "<cachedir>/var/cache/fontconfig</cachedir>" "<cachedir>${TMPDIR}/var/cache/fontconfig</cachedir>"
fontconfreplace "<cachedir prefix=\"xdg\">fontconfig</cachedir>" ""
fontconfreplace "<cachedir>~/.fontconfig</cachedir>" ""

export PATH="${ROOT}/usr/bin:${PATH}"
export FONTCONFIG_PATH="${TMPDIR}/etc/fonts"
"${ROOT}/opt/browservice/browservice" "$@"
